In [8]:
import os
import pandas as pd

base_url = 'https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/'
anime_csv = os.path.join(base_url,'anime.csv')

df = pd.read_csv(anime_csv,dtype={'members':float})
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630.0
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665.0
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262.0
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572.0
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266.0

In [9]:
import os
import pandas as pd

base_url = 'https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/'
anime_csv = os.path.join(base_url,'anime.csv')

anime_stock_price_csv = os.path.join(base_url,'anime_stock_price.csv')
df = pd.read_csv(anime_stock_price_csv,parse_dates=['Date'])
df.dtypes

Date              datetime64[ns]
TOEI ANIMATION           float64
IG Port                  float64
dtype: object

In [16]:
import os
import pandas as pd

base_url = 'https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/'
anime_tsv = os.path.join(base_url,'anime.tsv')

df = pd.read_csv(anime_tsv, sep='\t')

In [19]:
import os
import pandas as pd

base_url = 'https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/'
anime_xlsx = os.path.join(base_url,'anime.xlsx')

df = pd.read_excel(anime_xlsx,sheetname='Movie')
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
2,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733
3,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
4,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193

In [3]:
import os
import pandas as pd

from urllib.request import urlopen
import sqlite3

anime_db = os.path.join(base_url,'anime.db')
res = urlopen(anime_db)
with open('anime.db','wb') as f:
    f.write(res.read())
    with sqlite3.connect(f.name) as conn:
        df = pd.read_sql('SELECT * FROM anime', conn)

NameError: name 'base_url' is not defined

In [1]:
import os
import pandas as pd

url = 'https://docs.python.org/3/py-modindex.html'

tables = pd.read_html(url,index_col=1)
tables[0].loc[:,1:].dropna().head(10)

                                                               2
1
__future__                          Future statement definitions
__main__       The environment where the top-level script is ...
_dummy_thread        Drop-in replacement for the _thread module.
_thread                                 Low-level threading API.
abc                 Abstract base classes according to PEP 3119.
aifc           Read and write audio files in AIFF or AIFC for...
argparse       Command-line option and argument parsing library.
array          Space efficient arrays of uniformly typed nume...
ast               Abstract Syntax Tree classes and manipulation.
asynchat       Support for asynchronous command/response prot...